name: travel_hour
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  the_apple_sign_in: ^1.1.1
  animated_bottom_navigation_bar: ^1.1.0
  cached_network_image: ^3.2.2
  carousel_pro: ^1.0.0
  cloud_firestore: ^4.1.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.0
  dots_indicator: ^2.1.0
  easy_localization: ^3.0.1
  google_mobile_ads: ^2.3.0
  # facebook_audience_network: ^0.7.1
  # flutter_facebook_login: ^3.0.0
  firebase_analytics: ^10.0.6
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  firebase_storage: ^11.0.6
  firebase_in_app_messaging: ^0.7.0+6
  flare_flutter: ^3.0.2
  flutter_html: ^3.0.0-alpha.6
  flutter_icons: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_widget_from_html: ^0.9.0+1
  flutter_polyline_points: ^1.0.0
  geo: ^0.3.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  google_sign_in: ^5.4.2
  html: ^0.15.1
  html_unescape: ^2.0.0
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  launch_review: ^3.0.1
  line_icons: ^2.0.1
  md2_tab_indicator: ^1.0.2
  package_info: ^2.0.2
  provider: ^6.0.4
  share: ^2.0.4
  shared_preferences: ^2.0.15
  skeleton_text: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  toast: ^0.3.0
  url_launcher: ^6.1.7




  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"






flutter:

  uses-material-design: true






  assets:
    - assets/images/search.png
    - assets/images/travel1.png
    - assets/images/travel2.png
    - assets/flr/success.flr
    - assets/images/travel4.png
    - assets/images/travel5.png
    - assets/images/travel6.png
    - assets/images/empty.png
    - assets/images/restaurant.png
    - assets/images/hotel.png
    - assets/images/splash.png
    - assets/images/icon.png
    - assets/images/hotel_pin.png
    - assets/images/restaurant_pin.png
    - assets/images/destination_map_marker.png
    - assets/images/driving_pin.png
    - assets/translations/

  fonts:

    - family: Muli
      fonts:
        # - asset: fonts/Montserrat-Light.ttf
        #   weight: 400
        - asset: fonts/Muli-Regular.ttf
          weight: 500
        - asset: fonts/Muli-Medium.ttf
          weight: 600
        - asset: fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: fonts/Muli-Bold.ttf
          weight: 800
